jest:
  data:
    elasticsearch:
      # es集群节点  http://localhost:9200
      urls:
        - 'http://localhost:9200'
      # 设置连接es的用户名和密码
      account:
        username: elastic
        password: 12345
